version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.0
    working_directory: ~/psst
    steps:
      - checkout
      - run:
          name: Run tests
          command: make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build